spring:
  profiles:
      active: dev

  datasource:
    url: jdbc:p6spy:mariadb://15.164.85.142:3306/freelancer_project
    username: admin
    password: admin123!!
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

  data:
    redis: # ← 여기 들여쓰기 수정됨
      host: 15.164.85.142
      port: 6379
      password: redis123!!

    jpa:
      database: mysql
      database-platform: org.hibernate.dialect.MariaDBDialect #마리아db문법에 맞춤
      generate-ddl: true
      show_sql: ture
      hibernate:
#       ddl-auto: create
        ddl-auto: update
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_batch_fetch_size:100

  mail:
    host: smtp.gmail.com
    port: 587
    username: freelancer.service.platform@gmail.com
    password: ptin kuad wzoy hlen
    protocol: smtp
    tls: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB # 업로드할 수 있는 개별 파일의 최대 크기. 기본 1MB
      max-request-size: 10MB #multipart/form-data 요청의 최대 허용 크기. 기본 10MB


# Google 로그인 API
  security: 
    oauth2: 
      client: 
        registration:
          google:
            client-id: 861271781628-76v5ct3i1qm07u5fgksg0l9in6vkqlfu.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/google"

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8080
  # address: 0.0.0.0
  servlet:
    context-path: /api
  tomcat:
    max-http-form-post-size: 10MB

jwt:
  secret: MySuperSecretKeyForJWTEncoding123456
  access-token-expiration: 1800000
  refresh-token-expiration: 1209600000

# 기업 인증 API
external:
  business-verify:
    api-key: oo7Cptu/muq0VdvJOvEZ816dEyBChjhrqLIM0HqL2+eJeZXKg46MztkspSRsh3HBX/lyqoXbNCWB4OydznQ+mg== #

logging:
  level:
    root: INFO
    # org.hibernate.SQL: DEBUG # JPA SQL 출력
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE # 바인딩된 파라미터 출력
    org.mybatis: INFO # MyBatis SQL 출력
    org.springframework.transaction: DEBUG # 트랜잭션 처리 흐름
    org.apache.ibatis: INFO
    org.springframework.jdbc.datasource: WARN
    com.zaxxer.hikari: WARN

# AWS S3
cloud:
  aws:
    credentials:
      access-key: AKIA2KX4BVZJYO6C4VES
      secret-key: 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
    region:
      static: ap-northeast-2 # 버킷의 리전
    s3:
      bucket: freelancer-project-bucket3 # 버킷 이름
    stack:
      auto: false


# Naver 지도 API
naver:
  map:
    client-id: soeyw6whad
    client-secret: W1hOx8vv6k6lrn2ycpj5lvL1TDlR6dX0e0QGw0kZ
